services:
    db:
        image: postgres:latest
        container_name: blog-fastapi
        environment:
            - POSTGRES_USER=POSTGRES_DB_USER
            - POSTGRES_PASSWORD=POSTGRES_DB_PASSWORD
            - POSTGRES_DB=POSTGRES_DB_NAME
        ports:
            - '5456:5432'
        volumes:
            - postgres-data:/var/lib/postgresql/data
        restart: always
        networks:
            - blog-network

volumes:
    postgres-data:

networks:
    blog-network:
        driver: bridge
