"""fixed blog list, get blog by id, and get blog by slug

Revision ID: 03b98b2bb34d
Revises: a8110f96518e
Create Date: 2025-06-14 12:17:01.959956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03b98b2bb34d'
down_revision: Union[str, None] = 'a8110f96518e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
