"""creating new user

Revision ID: 54fa2748c54b
Revises: 7fb495964381
Create Date: 2025-06-07 18:41:38.384599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54fa2748c54b'
down_revision: Union[str, None] = '7fb495964381'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'author_id')
    # ### end Alembic commands ###
