"""Creating Category

Revision ID: bae9cad1df0b
Revises: 3f5fecd49a17
Create Date: 2025-06-10 10:39:21.618024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bae9cad1df0b'
down_revision: Union[str, None] = '3f5fecd49a17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('slug', sa.String(), nullable=False))
    op.add_column('categories', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column('categories', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'categories', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'created_at')
    op.drop_column('categories', 'author_id')
    op.drop_column('categories', 'slug')
    # ### end Alembic commands ###
